### ISSUE TITLE
Consistent application of patterns

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#10]
I have noticed that pattern of reference is used inconsistency across different entity and APIs.
* naming convention vary: sometimes `Ref` postfix is used sometimes not
* attributes can vary - sometimes reference with `id` and `href` is used, in other cases there is an `id` by itself, or there is a number of extra fields in the reference entity

Another example is a state of an entity - I guess for different entities there are different state machines but maybe it would be beneficial to use the same state name for states that means the same?

**Comment by MichalLaczynskiAmartus** [comment]
@bartoszm I think we can close this one?
