### ISSUE TITLE
[IIS-POQ] Mapping between use cases and API calls

### ISSUE THREAD

**Issue by mariusz-amartus** [MEF-GIT/MEF-LSO-Sonata-SDK#117]
Sonata IIS - Product Offering Qualification Management
Content:
7. Detailed description
a. Mapping between use cases and API calls

**Comment by bigludo7** [comment]
@fahimsabir-colt could you please share with me the nice bpmn you did ?
I could re use this doc in this part probably.
Thanks

**Comment by fahimsabir-colt** [comment]
A bpmn file can be found on the contribution page for the Karthik's API Ad-hoc.  I didn't draw it, but it is very well put together so I would recommend its use.

**Comment by bigludo7** [comment]
Work in progress - first draft uploaded on contribution page
