### ISSUE TITLE
GET /geographicSite does not allow Geographic Address ID to be given as a parameter

### ISSUE THREAD

**Issue by fahimsabir-colt** [MEF-GIT/MEF-LSO-Sonata-SDK#12]
It is not possible to specify a Geographic Address ID as a parameter to GET /geographicSite to get a list of sites associated with just that Geographic Address ID.

It should be possible to validate an address to yield an identifier, and then immediately get a list of sites for that address.

**Comment by bigludo7** [comment]
Implemented.
