### ISSUE TITLE
Create New Product Order - Response code 422 Duplicated Error code 114

### ISSUE THREAD

**Issue by Imorency** [MEF-GIT/MEF-LSO-Sonata-SDK#128]
In the Create New Product Order, Response code 422, the Error code 114 is duplicated.

**Comment by Imorency** [comment]
Salut Ludovic, In order to solve this duplication, is the plan to replace the Error Code 114 by a new Error Code for the message "Missing Seller at order level" or for the message "A recurring price is mentioned without a charge period"?  If yes, has the new Error Code been decided?

**Comment by bigludo7** [comment]
Bonjour Isabelle
114: A reccuring price is mentionned without a charge period.
119: Missing Seller at order level

**Comment by MichalLaczynskiAmartus** [comment]
RC5 introduces new approach to Errors. No longer we produce subcodes for each possible thing that can happen. There are several types of errors that may occur and an extra JSONpath field that will point to the attribute causing the problem.
