### ISSUE TITLE
Incompatible date formatting for requestedResponseDate

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#131]
[POQ#requiredResponseDate](https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/7cd1c9187ae57c2d4e15a71fb05013e9acc2bf05/api/Serviceability/MEF_api_productOfferingQualificationManagement_3.0.1.yaml#L764) has different string formating than in other places:
[POQ_Create#requiredResponseDate](https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/7cd1c9187ae57c2d4e15a71fb05013e9acc2bf05/api/Serviceability/MEF_api_productOfferingQualificationManagement_3.0.1.yaml#L858) and [POQ_Find#requiredResponseDate](https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/7cd1c9187ae57c2d4e15a71fb05013e9acc2bf05/api/Serviceability/MEF_api_productOfferingQualificationManagement_3.0.1.yaml#L911). In first place it is date-time wheras in others just date.

The same problem appears in json version of definition

**Comment by MichalLaczynskiAmartus** [comment]
Fixed
