### ISSUE TITLE
Wrong type in POQItem state change

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#132]
POQ Item#stateChange refers to StateChange definition (which is also used at POQ level)
State change itself refers to ProductOfferingQualificationStateType.
The problem is that POQ Item #state is of type ProductOfferingQualificationItemStateType whereas POQ Item #stateChange is (effectively) of type ProductOfferingQualificationStateType

**Comment by MichalLaczynskiAmartus** [comment]
fixed
