### ISSUE TITLE
Remove the enumeration from product and item relationships

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#133]
We should consider removing relationship type from Swagger specification (ideally in all API definitions and specification encodings (json | yaml)

Although we should be able to constrain the type of relationship between items and products it should not be decided at the API level but rather than on a product specification level (e.g. relation between Access ELine and UNI might be different than between other product types).
Therefore we should remove [RelationType](https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/7cd1c9187ae57c2d4e15a71fb05013e9acc2bf05/api/Serviceability/MEF_api_productOfferingQualificationManagement_3.0.1.yaml#L465) from the sdec and make the relation free form text - to move the responsibility for defining the relation type from API to product specific definitions.

**Comment by bigludo7** [comment]
I did the modification for the POQ but must be also done for other API - Please keep this issue open.

**Comment by MichalLaczynskiAmartus** [comment]
All API now without the enum
