### ISSUE TITLE
Encapsulate product specific attributes under common parent node

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#134]
Per MEF IIS discussion:
We can add the `characteristics`  (we can choose better name if needed) container into `Product` definition to group product specific attributes in a single json node. 
This should introduce clear separation of product specific attributes and make it easier to implement various payload validation and binding strategies that will be interoperable with each other.

**Comment by bigludo7** [comment]
I can implement this in Sonata API swaggers.

**Comment by MichalLaczynskiAmartus** [comment]
not relevant anymore due to the new Product specification pattern. Please refer to MEF W87.
