### ISSUE TITLE
RelatedPlaceReforValue inconsistent name

### ISSUE THREAD

**Issue by softdevadamlach** [MEF-GIT/MEF-LSO-Sonata-SDK#139]
Here:
[Order](https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/ad464b58c470ba7e23da37a98e4f54debb04e0e9/api/ProductOrder/MEF_api_productOrderManagement_3.0.1.yaml#L1008)
and here:
[POQ](https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/working-draft/api/Serviceability/MEF_api_productOfferingQualificationManagement_3.0.1.yaml#L920)

the class name is "RelatedPlaceRef**o**rValue"

Here:
[Quote](https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/ad464b58c470ba7e23da37a98e4f54debb04e0e9/api/Quote/MEF_api_quoteManagement_2.0.0.yaml#L1032)
the class name is "RelatedPlaceRef**O**rValue"

The capital letter "O" in all places should be implemented in all places.

**Comment by bigludo7** [comment]
Agreed on the issue.

**Comment by MichalLaczynskiAmartus** [comment]
Fixed
