### ISSUE TITLE
swagger definition of ProductSpecificationRef in Quote corrupted 

### ISSUE THREAD

**Issue by softdevadamlach** [MEF-GIT/MEF-LSO-Sonata-SDK#140]
discriminator property for ProductSpecificationRef is wrongly used here:

https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/ad464b58c470ba7e23da37a98e4f54debb04e0e9/api/Quote/MEF_api_quoteManagement_2.0.0.yaml#L1010

line should be deleted. Discriminator is a field for inheritance.

**Comment by MichalLaczynskiAmartus** [comment]
Not applicable. ProductSpecificationRef is removed from Quote
