### ISSUE TITLE
Typo in API GeographicAddressManagement

### ISSUE THREAD

**Issue by Harjindar** [MEF-GIT/MEF-LSO-Sonata-SDK#143]
In the [swagger file](https://raw.githubusercontent.com/MEF-GIT/MEF-LSO-Sonata-SDK/r4/api/Serviceability/MEF_api_geographicAddressManagement_3.0.0.json), the word address is misspelled two times as "adress"

**Comment by MichalLaczynskiAmartus** [comment]
Fixed
