### ISSUE TITLE
Findings during implementation of Sonata Quote API

### ISSUE THREAD

**Issue by Harjindar** [MEF-GIT/MEF-LSO-Sonata-SDK#144]
I'm not sure whether I should create separate issues or list them all together in one issue. For now I'm mentioning them here and if required I'll create separate issues:

MEF Sonata API gives us a good foundation to build our API’s. The challenges are more in details. For e.g. 

- A high level picture of the API interactions starting from Address Management, to Serviceability, Quote Api Management and Order Api Management. This is useful for a newcomer

- Sonata Swagger should contain a good documentation about the field description. Now we’ve to move back and forth between pdf’s and swagger to understand the exact business meaning of a field (Eg. missing details in swagger about Product Offering Id and Product Id.
- Fields not defined properly in any documentation like RelationshipType (COMES_FROM, BUNDLED) etc
- Only basic error codes defined and not functional ones.

**Comment by bigludo7** [comment]
Hello
Probably helpful if you create specific issue for each of your finding requiring a swagger correction. 
Some point you're mentionning will be addressed in the IIS documentation (project lead by @bartoszm ).

**Comment by MichalLaczynskiAmartus** [comment]
With Release Candidate 5 the API will be hugely updated. There is also MEF 115 - Quote Developer Guide being edited, which will answer or correct your issues. You can take a look on the MEF project: https://wiki.mef.net/display/LSO/LSO+Sonata+IIS+-+Project+Home+Page

**Comment by Harjindar** [comment]
Hi @MichalLaczynskiAmartus,
Is there any draft version of the Developer Guide already available. Tried to search in MEF wiki but couldn't find any.

**Comment by MichalLaczynskiAmartus** [comment]
Hi,

The version of the document is in very early stages. The focus was to deliver a good API for this release.
You can find it on page:
https://wiki.mef.net/display/LSO/MEF+W115+%28LSO+Sonata+Quote+Management-+Interface+Implementation+Specification%29+-+Home+Page
in the latest contribution.
If you are interested in the works - I encourage you to join the Dev Guide calls and support.

**Comment by MichalLaczynskiAmartus** [comment]
With Sonata Aretha release there are 4 Developer Guides attached. We hope that helps. Shall you have any more question, please contact community_manager@mef.net or raise an issue.
