### ISSUE TITLE
QuoteItem refers to Array/one POQ - inconsistency in definitions

### ISSUE THREAD

**Issue by softdevadamlach** [MEF-GIT/MEF-LSO-Sonata-SDK#145]
Inconsistency between QuoteItem_Create and QuoteItem definition exists in the MEF_api_quoteManagement_2.0.0 definition 

In QuoteItem_Create reference to POQ is an **object**
https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/ad464b58c470ba7e23da37a98e4f54debb04e0e9/api/Quote/MEF_api_quoteManagement_2.0.0.yaml#L1103

In QuoteItem_Create reference to POQ is an **array of objects**
https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/ad464b58c470ba7e23da37a98e4f54debb04e0e9/api/Quote/MEF_api_quoteManagement_2.0.0.yaml#L765

I think that array is a bug and Quote Item should be referred to one Poq Item

**Comment by MichalLaczynskiAmartus** [comment]
Fixed.
In fact, now the TMForm's ProductOfferingQualificationItemRef is used, but consistently
