### ISSUE TITLE
Product.id should not be required on Quote INSTALL

### ISSUE THREAD

**Issue by softdevadamlach** [MEF-GIT/MEF-LSO-Sonata-SDK#146]
Product.id should not be required here:
https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/ad464b58c470ba7e23da37a98e4f54debb04e0e9/api/Quote/MEF_api_quoteManagement_2.0.0.yaml#L824

When the product is "Installed", product.id appears for the first time during Ordering. So for Quote model it is not required.

**Comment by bigludo7** [comment]
Quote is operation-agnostic meaning same API structure will be used for any operation; Product.id will be required for any update quote request.
So no change is the swagger required but your point must be documented in the associated documentation (if action is add, product id must not be provided).

**Comment by bartoszm** [comment]
I think change to swagger is required. The codegen tools are using "required" fields for payload modification. So given Product#id is required, you will need to modify generated code manually to remove validation logic.

**Comment by MichalLaczynskiAmartus** [comment]
Fixed.
