### ISSUE TITLE
Remove PoqItemEvent from definitions

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#150]
https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/ad464b58c470ba7e23da37a98e4f54debb04e0e9/api/Serviceability/MEF_api_productOfferingQualificationNotification_3.0.0.yaml#L216

It is not used by other definitions thus there is no need to keep it in swagger.

**Comment by bigludo7** [comment]
Removed as well enum for QualificationState & ServiceabilityColor

**Comment by MichalLaczynskiAmartus** [comment]
Fixed
