### ISSUE TITLE
Use MapCharacteristic to model MEF product definitions in POQ

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#151]
We have an ongoing discussion on how to model product definitions in API. This change proposes to use TMF characteristic pattern in a way that we use a single specialization of the pattern - namely `MapCharacteristic`  - to encapsulate full MEF Product attributes tree.

**Comment by MichalLaczynskiAmartus** [comment]
Implemented in all APIs with a different pattern, as described in MEF W87
