### ISSUE TITLE
Desired Responses Attribute written with and without an 's' in the schema

### ISSUE THREAD

**Issue by Imorency** [MEF-GIT/MEF-LSO-Sonata-SDK#152]
In the schema, the Desired Responses attribute is written with an 's' in some places and without an 's' in some other places.   'desiredResponses' vs 'desiredResponse'.  These should be aligned.

**Comment by bigludo7** [comment]
Corrected on my working space.
Please note that I understood this attribute will move at product item level with 57.2.

**Comment by MichalLaczynskiAmartus** [comment]
aligned to version without "s"
