### ISSUE TITLE
formattedAdress should be formattedAddress

### ISSUE THREAD

**Issue by gythialy** [MEF-GIT/MEF-LSO-Sonata-SDK#153]
https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/95ef8fd163a78977b0ded94fda01be2f38a2303c/api/Serviceability/MEF_api_geographicSiteManagement_3.0.0.yaml#L350

https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/95ef8fd163a78977b0ded94fda01be2f38a2303c/api/Serviceability/MEF_api_geographicSiteManagement_3.0.0.json#L479

https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/95ef8fd163a78977b0ded94fda01be2f38a2303c/api/R4%20release%20notes.txt#L49

**Comment by MichalLaczynskiAmartus** [comment]
@bigludo7 can you please take a look at that?

**Comment by gythialy** [comment]
and other typo, `additionnalSiteInformation`->`additionalSiteInformation`

https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/blob/95ef8fd163a78977b0ded94fda01be2f38a2303c/api/Serviceability/MEF_api_geographicSiteManagement_3.0.0.yaml#L329

**Comment by bigludo7** [comment]
Thanks. I've corrected both on my work version
