### ISSUE TITLE
Error Code 109

### ISSUE THREAD

**Issue by Imorency** [MEF-GIT/MEF-LSO-Sonata-SDK#154]
The description of Error code: 109 is: If orderActivity is set to INSTALL, all orderItemAction must be INSTALL. 
It should be: If orderActivity is set to INSTALL, all orderItemAction must be ADD.

**Comment by MichalLaczynskiAmartus** [comment]
@bigludo7 Can you take a look?

**Comment by bigludo7** [comment]
Yes this is a bug - Fixed on my environnement.

**Comment by MichalLaczynskiAmartus** [comment]
RC5 introduces new approach to Errors. No longer we produce subcodes for each possible thing that can happen. There are several types of errors that may occur and an extra JSONpath field that will point to the attribute causing the problem.
