### ISSUE TITLE
Attribute 'role' in globalAddressId in GeographicSite API

### ISSUE THREAD

**Issue by bigludo7** [MEF-GIT/MEF-LSO-Sonata-SDK#157]
Why a role attribute added in the globalAddressID in the GeographicSite API?
We do not have any role for other place descriptor. This attribute was not in the previous release.
Moreover this role is tagged as mandatory :(

**Comment by MichalLaczynskiAmartus** [comment]
This will be fixed in RC 5.1

**Comment by MichalLaczynskiAmartus** [comment]
Resolved
