### ISSUE TITLE
Quote has a different structure for specifying product relationships from Qualification

### ISSUE THREAD

**Issue by fahimsabir-colt** [MEF-GIT/MEF-LSO-Sonata-SDK#22]
The structure for a product relationship in Quote is:

```
        "productRelationship": [
          {
            "type": "RELIES_ON",
            "product": {
              "id": "string"
            }
          }
        ],
```

whereas Qualification uses the following structure:
```
        "productRelationship": [
          {
            "type": "RELIES_ON",
            "id": "string"
          }
        ],
```

This should be rationalised.  And also with Order.
The more concise format should be used (i.e. the one currently in Qualification).

**Comment by bigludo7** [comment]
It depends for me if we want to add the href for the targeted product (we have an issue logged on this).

- if yes, I will prefer to keep the productRef class with id + href
- if no, I'm ok with the concise format.

**Comment by fahimsabir-colt** [comment]
I'm not sure why one precludes the other.  I'd like the flat structure and href :-)

**Comment by bigludo7** [comment]
For me consistency within all our APIs.... Here the id (and the href) are _product_ information and not _productRelationship_ information. In all other structure the id and href are always referring the 'node'. That why I prefer to have a 'node' product within this productRelationship.

**Comment by bigludo7** [comment]
Implemented
