### ISSUE TITLE
Do we need to embedded 'Place' schema in API swaggers ?

### ISSUE THREAD

**Issue by bigludo7** [MEF-GIT/MEF-LSO-Sonata-SDK#23]
Following first developper feedback, the schema location pattern is tough to implement.

In order to make life simpler for dev, the proposal is to have the place schema inserted directly in the API (productOfferingQualification, quote, productOrder) and avoiding schema location use. The place class is still use and the @type attribute will be considered as a discriminator to the place schema used.

Looking for feedbacks.

**Comment by fahimsabir-colt** [comment]
Superficially it sounds like it would be an improvement but can you give an example of what this would look like in the Swagger?

**Comment by bigludo7** [comment]
Hi Fahim,

UC to illustrate (simplified): 
In product Order we have to define a ‘place’ where to deliver product. Place could be either described by ‘fieldedAddress’ or ‘formattedAddress’.
We add these 2 structures in the swagger.

I'm not sure we need to have the discriminator attribute. For me this is not required so I think we can remove it but looking for feedbacks.

Swagger:

```
    {
    "swagger": "2.0",
    "info": {
    "description": "",
    "version": "0.1.0_inProgress",
…
   "**definitions**": {
….
    "Place": {
    "description": "Place defines the places where the ordered products are sold or delivered.",   
    "required": [
    
      "@type",
      "role"
    ],
    "type": "object",
    "discriminator": "@type"
    "properties": {
    "id": {
    "description": "Unique identifier of the place.",
    "type": "string"
    },
…
    "FormattedAddress": {
    "description": "",   
      "allOf": [
      {
      "$ref": "#/definitions/Place"
      },
      {  
    "type": "object",
    "properties": {
    "streetName": {
    "description": "",
    }
    "streetNumber": {
…
    }
    }
    },
    "FieldedAddress": {
    "description": "",  
      "allOf": [
      {
      "$ref": "#/definitions/Place"
      },
      {   
    "required": [
      "addressLine1"
    ],
    "type": "object",
    "properties": {
    "addressLine1": {
    "description": "",
    }
```

Instantiation:

```
{
  externalId": "examplee658",
  "orderItem": [
    {
      "id": "1",
      "action": "add",
      "product": {
…
        },
        "place": [
          {
            "role": "installationPlace",
            "@type": " FormattedAddress ",
            "streetName": "Felix Faure",
            "streetNumber": 14,
          }
        ],
…
    }
  ]
}
```

**Comment by fahimsabir-colt** [comment]
OK.. I understand.  My personal view: the Swagger MUST use the discriminator directive.

**Comment by bigludo7** [comment]
Implemented
