### ISSUE TITLE
UNI product doesn't allow the specification of a connector

### ISSUE THREAD

**Issue by fahimsabir-colt** [MEF-GIT/MEF-LSO-Sonata-SDK#25]
It is possible to specify the Physical Layer (e.g. 1000BASE-T etc) but not the Physical Connector (e.g. RJ-45).

This is important to customers when discussing with them what is going to be delivered, as well as when transacting with them. It must be possible to specify this in the configuration passed in Qualification, Quote, and Order.

**Comment by MichalLaczynskiAmartus** [comment]
In new spec by MEF W106 there is "connectorType" present with  "enum": ["SC", "LC", "RJ45", "OTHER"]
