### ISSUE TITLE
Define several business errors 'behind' HTTP 422

### ISSUE THREAD

**Issue by bigludo7** [MEF-GIT/MEF-LSO-Sonata-SDK#26]
This issue is related to **ALL** Sonata API.
As of now, only one error could be send with the error message 422. We should extend to be able to send several sub-error within one 422 error message.

**Comment by MichalLaczynskiAmartus** [comment]
RC5 introduces new approach to Errors. No longer we produce subcodes for each possible thing that can happen. There are several types of errors that may occur and an extra JSONpath field that will point to the attribute causing the problem.
