### ISSUE TITLE
POQ and Quote Items should have an action attribute in alignment to the Order Item definition

### ISSUE THREAD

**Issue by fahimsabir-colt** [MEF-GIT/MEF-LSO-Sonata-SDK#34]
POQ and Quote items should have an action attribute (with values INSTALL, CHANGE, DISCONNECT, NO_CHANGE) to align with the definition of an Order Item.

**Comment by bigludo7** [comment]
It is already aligned for the Quote item.

```
action* | QuoteItemActionstringQuote item actionEnum:[ INSTALL, CHANGE, DISCONNECT, NO_CHANGE ]
-- | --
```

But we do not have action at POQ item level and it could make sense to add it and align enum value.
I suggest to remove quote from this issue and only consider it for POQ.
