### ISSUE TITLE
ProductOrder reference in product inventory API is inconsistent

### ISSUE THREAD

**Issue by bigludo7** [MEF-GIT/MEF-LSO-Sonata-SDK#39]
Currently in the product inventory API, we have following sub node:
 
```
 "productOrderItem": [
    {
      "id": "string",
      "href": "string",
      "productOrderId": "string"
    }
  ],
```

This is confusing because the id is the product order item id but the href is the product order one.
May i suggest to change this ?

  "productOrder": [
    {
      "id": "string",
      "href": "string",
      "orderItemId": "string",
    }
  ],

It's more clear...the node is productOrder and id and href are product order ones. OrderItemId allows to link to the correct item.

**Comment by fahimsabir-colt** [comment]
+1

**Comment by bigludo7** [comment]
April 3rd - team meeting - OK for suggested proposal.

**Comment by bigludo7** [comment]
Implemented
