### ISSUE TITLE
Dynamic extension mechanism markers (e.g. @type) should be used with caution

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#4]
Dynamic extension "markers" (for not better word) like `@type` ,`@baseType`, and `@schemaLocation` should be added only to the classes when API allows for dynamic extension.

For general purpose swagger generators they have not meaning other that _an attribute_.

We could consider using more standard swagger approach instead/in addition to these customized attributes - e.g. consider using `additionalProperties` section in swagger definition.

Maybe as MEF team we could discuss with TMF the best strategy to address dynamic extension pattern (in TMF630 Part 2 page 20 using `allOf` as extension mechanism is recommended however this will address more static extensibility patterns).

**Comment by MichalLaczynskiAmartus** [comment]
Is this addressed already?

**Comment by bartoszm** [comment]
yes it is
