### ISSUE TITLE
Pricing structure in Quote is much too complex

### ISSUE THREAD

**Issue by fahimsabir-colt** [MEF-GIT/MEF-LSO-Sonata-SDK#41]
The pricing structure supported in Quote is much too complex, and should initially support:

1. Name of charge
1. Type of charge (recurring vs non-recurring)
1. Recurrence interval (HOUR, DAY, MONTH, YEAR) if recurring
1. currency
1. Duty free amount

Building out a more robust model should be for further study.

**Comment by bigludo7** [comment]
implemented
