### ISSUE TITLE
RelatedPlaceReforValue.type defined as an open string

### ISSUE THREAD

**Issue by Imorency** [MEF-GIT/MEF-LSO-Sonata-SDK#49]
This is defined as an open string but only has set values allowed "Site", "FormattedAddress", "FieldedAddress", "ReferencedAddress", or "GeographicLocation".  Suggestion: An enum property can be added to allow this field to be validated through schema validation.

**Comment by bigludo7** [comment]
I'm always a bit cautious with enum because it locks a bit the API. I will prefer to handle this with a rule and a 422+ message if the value is not in the list. It will allows us to let SP remove or add place type without hard change on the API. Just me perspective on this.

**Comment by bigludo7** [comment]
Proposal: keep as a string. IISW will feature list of valid value. we add a 422 +xxx error to indicate "unrecognized place type" to track when buyer provide unexpected place type value.

**Comment by MichalLaczynskiAmartus** [comment]
Agree with Ludovic. Please refer to MEF W87.
