### ISSUE TITLE
Describe extension specification model in developer guide

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#5]
For purpose of this description the extensions are the custom types defined in [PlaceDescription](master/experimental/api/PlaceDescription) and [ProductSpecDescription](master/experimental/api/ProductSpecDescription).

The extension specification model should be described in some type of developer guide.
To me it looks like  json-schema http://json-schema.org/ definition - anyone from the team can confirm?
It would be useful to put somewhere in the repository an example of automation (verification, code generation etc.) using json-schema.

**Comment by bigludo7** [comment]
Following feedback from Developpers + discussion with @fahimsabir-colt we plan to integrate the place structure within the swagger (and tried to deliver this for Dubronik).
We have still the polymorphism pattern use for productSpec where from my perspective it's relevant to avoid a product-locked API ... challenge is to make this more easy to use for developper...

**Comment by MichalLaczynskiAmartus** [comment]
Product specification pattern agreed. Described in MEF W87
