### ISSUE TITLE
billingAccount/pricingMethod/pricingReference/pricingTerm

### ISSUE THREAD

**Issue by Imorency** [MEF-GIT/MEF-LSO-Sonata-SDK#52]
These four fields are used in the header and in the order item. Should they be moved to a separate object/reference to group all billing and pricing fields? They could then be referenced in both places.

**Comment by MichalLaczynskiAmartus** [comment]
billingAccount/pricingMethod are extracted.
pricingRefernece is just a ref, so it does not need to be.
pricingTerm is just a number.
