### ISSUE TITLE
Draft API backlog after spring/summer '19 work

### ISSUE THREAD

**Issue by bigludo7** [MEF-GIT/MEF-LSO-Sonata-SDK#58]
Hello
I began to list API impacts after work done on MEF79-80-81 during spriong and summer.
This document will be completed in coming week(s) and backlog items should be discussed & priorized.
[Backlog MEF API.xlsx](https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/files/3540411/Backlog.MEF.API.xlsx)

**Comment by bigludo7** [comment]
Version updated covering MEF79-80-81
[Backlog MEF API.xlsx](https://github.com/MEF-GIT/MEF-LSO-Sonata-SDK/files/3579240/Backlog.MEF.API.xlsx)

**Comment by bigludo7** [comment]
This issue sum-up a lot of issues - will not implemented as it but via individual issue like #66, #65, #64, etc.

**Comment by MichalLaczynskiAmartus** [comment]
I am closing
