### ISSUE TITLE
Design git repository for reuse of type definitions

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#6]
Swagger allows for composing definition using multiple files (using YAML language features) https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-8-splitting-specification-file/

We could consider to use this approach to reuse common type definitions e.g. `RelatedParty`.

**Comment by bigludo7** [comment]
Hi @bartoszm 
Agreed on the objective.
Are you following the current TMF schemafication exercice to build swagger from JSON schema. Each class is defined once and TMF tooling 'generate' swagger from this. 
I don't know if the tooling could be shared from TMF and MEF (and honestly not my job to check that) but from capability perspective I encourage you to take a look. I use this for crafting TMF API and it allows more consistence whoever is the author of the API.

**Comment by MichalLaczynskiAmartus** [comment]
We have now access to the TMF tooling so the goal is met.
