### ISSUE TITLE
move site attributes from RelatedPlaceReforValue to specific place descriptor

### ISSUE THREAD

**Issue by bigludo7** [MEF-GIT/MEF-LSO-Sonata-SDK#60]
When a site is used to describe place in an, order we should not offer to buyer the capability to fill siteName, siteCompanyName, siteCustomerName, additionnalSiteInformation because site is already existing and the productOrder must not modify site informatino (it is a distinct resource).

In order to do that I suggest to remove the 4 site attributes from RelatedPlaceRefOrValue class and add them in FieldedAddress, FormattedAddress, ReferencedAddress & GeoLocation classes.

**Comment by bigludo7** [comment]
Would like to get @Imorency & @fahimsabir-colt  feedbacks before to proceed.

**Comment by MichalLaczynskiAmartus** [comment]
Done already
