### ISSUE TITLE
[R3] Naming scheme for types in addressAPIswagger

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#7]
Address validation entity names might be misleading as we have
`AddressValidation`, `AddressValidationRequest`, `AddressRequestValidation`,

In addition is `validAddress` a proper name for input parameter - in my opinion it is more like address to validate.

**Comment by MichalLaczynskiAmartus** [comment]
@bartoszm is this still an issue?

**Comment by bartoszm** [comment]
yes
