### ISSUE TITLE
Consistent naming across different APIs

### ISSUE THREAD

**Issue by bartoszm** [MEF-GIT/MEF-LSO-Sonata-SDK#9]
I think that having consistent domain model that spans across different API is needed. 

There are two example how consistent naming is violated:
* different name is used for the same payload
* same name is used for different payload

One minimal example:

`RelatedPartyRef`, `RelatedParty` are the variation of the same entity for product qualification, inventory and order API. Can we reuse the same construct or distinguish by name if we want to keep them separate?

**Comment by bigludo7** [comment]
Hello @bartoszm 
I tried to make progress on this with Dubrovnik release.
Do not hesitate to provide feedback and pointt to be corrected.

**Comment by bartoszm** [comment]
@bigludo7 let's have this one closed - I will try to work with the most up-to-date version of API definitions and provide my comments in separate issues
